// Persistent configuration: ~/.code-mcp-gateway/config.yaml
//
// Shape (everything optional except `devices`):
//
//   defaults:
//     gateway: "https://code-mcp.tuanm.workers.dev"
//     gateway_token: "gw-..."
//     token: "dev-..."
//     timeout_ms: 300000
//   devices:
//     my-device:
//       gateway: "https://other.example.dev"   # optional per-device override
//       gateway_token: "gw-..."
//       token: "dev-..."
//       connected_at: "2026-01-01T00:00:00.000Z"
//
// The file holds secrets, so it is created 0600 inside a 0700 directory, and
// writes are atomic (temp file + rename) so a crash cannot truncate it.

import { chmodSync, existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { CliError } from "./errors.ts";

export interface DeviceEntry {
  gateway?: string;
  gateway_token?: string;
  token?: string;
  connected_at?: string;
  note?: string;
}

export interface Defaults {
  gateway?: string;
  gateway_token?: string;
  token?: string;
  timeout_ms?: number;
}

export interface Config {
  defaults: Defaults;
  devices: Record<string, DeviceEntry>;
}

export function defaultConfigPath(): string {
  const override = process.env.CODE_MCP_GATEWAY_CONFIG;
  if (override && override.trim().length > 0) return override.trim();
  return join(homedir(), ".code-mcp-gateway", "config.yaml");
}

export function emptyConfig(): Config {
  return { defaults: {}, devices: {} };
}

function asString(value: unknown): string | undefined {
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : {};
}

/** Parse the YAML text into a validated Config (never throws on unknown keys). */
export function parseConfig(text: string, source: string): Config {
  let raw: unknown;
  try {
    raw = Bun.YAML.parse(text);
  } catch (err) {
    throw new CliError(
      `invalid YAML in ${source}: ${err instanceof Error ? err.message : String(err)}`,
      "Fix the file, or delete it to start fresh.",
    );
  }
  if (raw === null || raw === undefined) return emptyConfig();
  if (typeof raw !== "object" || Array.isArray(raw)) {
    throw new CliError(`invalid config in ${source}: expected a YAML mapping at the top level`);
  }
  const doc = raw as Record<string, unknown>;
  const config = emptyConfig();

  const defaults = asRecord(doc.defaults);
  config.defaults = {
    gateway: asString(defaults.gateway),
    gateway_token: asString(defaults.gateway_token),
    token: asString(defaults.token),
    timeout_ms: typeof defaults.timeout_ms === "number" ? defaults.timeout_ms : undefined,
  };

  for (const [id, value] of Object.entries(asRecord(doc.devices))) {
    const entry = asRecord(value);
    config.devices[id] = {
      gateway: asString(entry.gateway),
      gateway_token: asString(entry.gateway_token),
      token: asString(entry.token),
      connected_at: asString(entry.connected_at),
      note: asString(entry.note),
    };
  }
  return config;
}

export function loadConfig(path: string): Config {
  if (!existsSync(path)) return emptyConfig();
  let text: string;
  try {
    text = readFileSync(path, "utf8");
  } catch (err) {
    throw new CliError(`cannot read ${path}: ${err instanceof Error ? err.message : String(err)}`);
  }
  if (text.trim().length === 0) return emptyConfig();
  return parseConfig(text, path);
}

/** Quote a scalar so the emitter is correct for any string content. */
function yamlScalar(value: string | number): string {
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "0";
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/[\x00-\x1f\x7f]/g, (c) => `\\x${c.charCodeAt(0).toString(16).padStart(2, "0")}`)}"`;
}

function emitSection(name: string, entries: Record<string, string | number | undefined>): string {
  const pairs = Object.entries(entries).filter(([, v]) => v !== undefined);
  if (pairs.length === 0) return "";
  let out = `${name}:\n`;
  for (const [key, value] of pairs) out += `  ${key}: ${yamlScalar(value as string | number)}\n`;
  return out;
}

/** Serialize deterministically: fixed key order, every string quoted. */
export function serializeConfig(config: Config): string {
  let out = "# code-mcp-gateway CLI configuration\n";
  out += "# Generated by 'mcp devices connect'. Holds secrets: keep it private (0600).\n";
  const defaults = emitSection("defaults", {
    gateway: config.defaults.gateway,
    gateway_token: config.defaults.gateway_token,
    token: config.defaults.token,
    timeout_ms: config.defaults.timeout_ms,
  });
  if (defaults) out += `\n${defaults}`;

  const ids = Object.keys(config.devices).sort();
  if (ids.length === 0) {
    out += "\ndevices: {}\n";
  } else {
    out += "\ndevices:\n";
    for (const id of ids) {
      const entry = config.devices[id]!;
      out += `  ${/^[A-Za-z0-9._-]+$/.test(id) ? id : yamlScalar(id)}:\n`;
      for (const [key, value] of [
        ["gateway", entry.gateway],
        ["gateway_token", entry.gateway_token],
        ["token", entry.token],
        ["connected_at", entry.connected_at],
        ["note", entry.note],
      ] as const) {
        if (value !== undefined) out += `    ${key}: ${yamlScalar(value)}\n`;
      }
    }
  }
  return out;
}

/** Atomic write with restrictive permissions. */
export function saveConfig(path: string, config: Config): void {
  const dir = dirname(path);
  try {
    mkdirSync(dir, { recursive: true, mode: 0o700 });
  } catch (err) {
    throw new CliError(`cannot create ${dir}: ${err instanceof Error ? err.message : String(err)}`);
  }
  const tmp = `${path}.${process.pid}.tmp`;
  try {
    writeFileSync(tmp, serializeConfig(config), { mode: 0o600 });
    renameSync(tmp, path);
  } catch (err) {
    try {
      rmSync(tmp, { force: true });
    } catch {}
    throw new CliError(`cannot write ${path}: ${err instanceof Error ? err.message : String(err)}`);
  }
  // rename() preserves the temp file mode, but an existing target could have had
  // looser permissions from a previous tool - enforce 0600 on the final path.
  try {
    chmodSync(path, 0o600);
  } catch {}
}
